configname: hg002_na24385_mix_nopass_sgd
data:
  flanking_size: 20
  max_depth: 200
  train: "na24385_f20_d10_a20_hg002_f20_d10_a5_nopass/train"
  dev: "na24385_f20_d10_a20_hg002_f20_d10_a5_nopass/validate"
  test: "None"
model:
  model_name: resnet50  # resnet18, resnet34, resnet50, resnet101, resnet152
  pretrained: True
  spp: False
  num_zy_class: 5
  num_gt_class: 16
  dropout: 0.5
  smoothing: 0.1
  use_gt_class_weight: False
training:
  batch_size: 64
  max_grad_norm: 1
  eval_or_not: True
  seed: 2024
  num_gpu: 1
  epochs: 45
  visualization: True
  save_model: hg002_na24385_mix_nopass_resnet50_sgd
optim:
  type: SGD # SGD, Adam, RMSprop
  lr: 0.01 # SGD: 0.01, Adam: 0.001, RMSprop: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  step_size: 30
  gamma: 0.1