configname: test_pileup
data:
  flanking_size: 20
  train: "hg002_isoseq_chr20_train_images"
  dev: "hg002_isoseq_chr19_train_images"
  test: "None"
model:
  model_name: "resnet18"  # resnet18, resnet34, resnet50, resnet101, resnet152
  num_class: 5
  dropout: 0.1
training:
  batch_size: 10
  use_balance: False
  validate_use_balance: False
  load_model: False
  first_stage: -1
  eval_or_not: True
  seed: 2024
  num_gpu: 0
  epochs: 200
  max_grad_norm: 20
  visualization: True
  save_model: test_pileup
optim:
  type: LookaheadAdam
  lr: 0.001
  momentum: 0.9
  nesterov: True
  decay_ratio: 0.98
  weight_decay: 0
  begin_to_adjust_lr: 10