configname: test_config
data:
  flanking_size: 20
  max_depth: 200
  train: "train"
  dev: "validate"
  test: "None"
model:
  model_name: resnet50  # resnet18, resnet34, resnet50, resnet101, resnet152
  pretrained: True
  spp: False
  num_zy_class: 5
  num_gt_class: 16
  dropout: 0.5
training:
  batch_size: 64
  max_grad_norm: 1.0
  eval_or_not: True
  seed: 2024
  num_gpu: 1
  epochs: 130
  visualization: True
  save_model: test_model
optim:
  lr: 0.001 # Radam: 0.001
  weight_decay: 0.0001
  warmup: 100
