configname: test
data:
  flanking_size: 20
  train: "train_dataset"
  dev: "validate_dataset"
  test: "None"
model:
  enc:
    type: lstm
    hidden_size: 64
    output_size: 128
    n_layers: 2
    bidirectional: True
  joint:
    inner_size: 256
  feature_dim: 38
  num_class: 4
  dropout: 0.3
training:
  batch_size: 200
  use_balance: False
  validate_use_balance: False
  load_model: False
  first_stage: -1
  eval_or_not: True
  seed: 2024
  num_gpu: 0
  epochs: 200
  max_grad_norm: 20
  visualization: True
  save_model: test
optim:
  type: LookaheadAdam
  lr: 0.001
  momentum: 0.9
  nesterov: True
  decay_ratio: 0.98
  weight_decay: 0
  begin_to_adjust_lr: 10